# Config

language: c
sudo: false
dist: buster
cache: bundler
notifications:
  email: false

env:
  - ASTVER=17

# Extend build matrix
matrix:
  include:
    - env: ASTVER=17

before_install:
  - tar jxf contrib/asterisk-$ASTVER.tar.bz2

before_script:
  - aclocal
  - autoconf
  - automake -a || true  # do install stuff, don't create makefile
  - ./configure --with-astversion=$ASTVER -with-asterisk=./asterisk-$ASTVER/include DESTDIR=/tmp

script:
  - make clean all
  - make check
