# Config

language: c
sudo: false
dist: buster
cache: bundler
notifications:
  email: false

env:
  - ASTVER=17.5.0

# Extend build matrix
matrix:
  include:
    - env: ASTVER=17.5.0
    - env: ASTVER=16.11.0

before_install:
  - curl -sSL http://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-${ASTVER}.tar.gz | tar xfz -
  - cd ./asterisk-$ASTVER && configure --prefix=/usr && make install-headers

before_script:
  - aclocal
  - autoconf
  - automake -a || true  # do install stuff, don't create makefile
  - ./configure --with-astversion=$ASTVER DESTDIR=/tmp

script:
  - make clean all
  - make check
